In [3]:
import numpy as np
import scipy

In [21]:
a = np.arange(9).reshape(3,3)

In [22]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
a[...] = np.asarray(np.arange(9).reshape(3,3))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
a[...]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])